List <String> randomNames = [
    "Sabichão",
    "Mestre do universo",
    "Sapo",
    "Sabe Nada Inocente",
    "Come Barriga",
    "Dorminhoco",
    "Lesma",
    "Fui no Banheiro",
    "Parceiro",
    "Perdido",
    "Truco!",
    "É a vez de quem?",
    "Zangado",
    "Rabugento",
    "Soneca",
    "Principiante",
    "Experiente",
    "Perdedor",
    "Rolê Aleatório",
    "Kléber",
    "Amarelão",
    "Rapador",
    "Pega Lixo",
    "Matusalém"
];